program azz;

uses
  Forms,
  Main in 'Main.pas' {frmMain},
  LogOn in 'LogOn.pas' {frmLogOn},
  NalashnuvannySistemi in 'NalashnuvannySistemi.pas' {frmNalashnuvannySistemi},
  Path in 'Path.pas' {frmPath},
  OdiniciVimiru in 'OdiniciVimiru.pas' {frmOdiniciVimiru},
  OdiniciVimiruEdit in 'OdiniciVimiruEdit.pas' {frmOdiniciVimiruEdit},
  ProProgramu in 'ProProgramu.pas' {frmProProgramu},
  Shtrafi in 'Shtrafi.pas' {frmShtrafi},
  ShtrafiEdit in 'ShtrafiEdit.pas' {frmShtrafiEdit},
  VidomchaPidporydkovanist in 'VidomchaPidporydkovanist.pas' {frmVidomchaPidporydkovanist},
  FinansoviSankciiEdit in 'FinansoviSankciiEdit.pas' {frmFinansoviSankciiEdit},
  FinansoviSankcii in 'FinansoviSankcii.pas' {frmFinansoviSankcii},
  Vruchenny in 'Vruchenny.pas' {frmVruchenny},
  AdminZapobizhZahodi in 'AdminZapobizhZahodi.pas' {frmAdminZapobizhZahodi},
  AdminZapobizhZahodiEdit in 'AdminZapobizhZahodiEdit.pas' {frmAdminZapobizhZahodiEdit},
  Objekti in 'Objekti.pas' {frmObjekti},
  ViluchennyZRealizaciiEdit in 'ViluchennyZRealizaciiEdit.pas' {frmViluchennyZRealizaciiEdit},
  ViluchennyZRealizacii in 'ViluchennyZRealizacii.pas' {frmViluchennyZRealizacii},
  Oskarzhenny in 'Oskarzhenny.pas' {frmOskarzhenny},
  KudiOskarzheno in 'KudiOskarzheno.pas' {frmKudiOskarzheno},
  KudiOskarzhenoEdit in 'KudiOskarzhenoEdit.pas' {frmKudiOskarzhenoEdit},
  Oskargenny in 'Oskargenny.pas' {frmOskargenny},
  OskargennyEdit in 'OskargennyEdit.pas' {frmOskargennyEdit},
  Splata in 'Splata.pas' {frmSplata},
  Statti in 'Statti.pas' {frmStatti},
  StattiEdit in 'StattiEdit.pas' {frmStattiEdit},
  Spivrobitniki in 'Spivrobitniki.pas' {frmSpivrobitniki},
  Raport in 'Raport.pas' {frmRaport},
  Posadi in 'Posadi.pas' {frmPosadi},
  Opechanuvanny in 'Opechanuvanny.pas' {frmOpechanuvanny},
  VidObmezhen in 'VidObmezhen.pas' {frmVidObmezhen},
  VidObmezhenEdit in 'VidObmezhenEdit.pas' {frmVidObmezhenEdit},
  NapravlenoDoVidoma in 'NapravlenoDoVidoma.pas' {frmNapravlenoDoVidoma},
  VidnovlennyRobit in 'VidnovlennyRobit.pas' {frmVidnovlennyRobit},
  Organizacii in 'Organizacii.pas' {frmOrganizacii},
  OrganizaciiEdit in 'OrganizaciiEdit.pas' {frmOrganizaciiEdit},
  LaboratornijKontrol in 'LaboratornijKontrol.pas' {frmLaboratornijKontrol},
  LaboratorniDoslidzhenny in 'LaboratorniDoslidzhenny.pas' {frmLaboratorniDoslidzhenny},
  LaboratorniDoslidzhennyEdit in 'LaboratorniDoslidzhennyEdit.pas' {frmLaboratorniDoslidzhennyEdit},
  Povidomlenny in 'Povidomlenny.pas' {frmPovidomlenny},
  ZayvaDoVDVS in 'ZayvaDoVDVS.pas' {frmZayvaDoVDVS},
  Napravlenny in 'Napravlenny.pas' {frmNapravlenny},
  NapravlennyEdit in 'NapravlennyEdit.pas' {frmNapravlennyEdit},
  SpivrobitnikiEdit in 'SpivrobitnikiEdit.pas' {frmSpivrobitnikiEdit},
  Ministry in 'Ministry.pas' {frmMinistry},
  PosadiEdit in 'PosadiEdit.pas' {frmPosadiEdit},
  Teritory in 'Teritory.pas' {frmTeritory},
  RajoniEdit in 'RajoniEdit.pas' {frmRajoniEdit},
  Rajoni in 'Rajoni.pas' {frmRajoni},
  ViddilennyEdit in 'ViddilennyEdit.pas' {frmViddilennyEdit},
  Viddilenny in 'Viddilenny.pas' {frmViddilenny},
  TeritoryEdit in 'TeritoryEdit.pas' {frmTeritoryEdit},
  MinistryEdit in 'MinistryEdit.pas' {frmMinistryEdit},
  TipiProdukcii in 'TipiProdukcii.pas' {frmTipiProdukcii},
  TipiProdukciiEdit in 'TipiProdukciiEdit.pas' {frmTipiProdukciiEdit},
  Rozdil_T23_F18 in 'Rozdil_T23_F18.pas' {frmRozdil_T23_F18},
  Rozdil_T23_F18Edit in 'Rozdil_T23_F18Edit.pas' {frmRozdil_T23_F18Edit},
  TipiShtrafiv in 'TipiShtrafiv.pas' {frmTipiShtrafiv},
  TipiShtrafivEdit in 'TipiShtrafivEdit.pas' {frmTipiShtrafivEdit},
  VidomostiProViluchenny in 'VidomostiProViluchenny.pas' {frmVidomostiProViluchenny},
  Virobniki in 'Virobniki.pas' {frmVirobniki},
  VidomostiProFinansovu in 'VidomostiProFinansovu.pas' {frmVidomostiProFinansovu},
  VirobnikiEdit in 'VirobnikiEdit.pas' {frmVirobnikiEdit},
  ObjektiEdit in 'ObjektiEdit.pas' {frmObjektiEdit},
  SotrudnikiObjektivEdit in 'SotrudnikiObjektivEdit.pas' {frmSotrudnikiObjektivEdit},
  VidPostanovi in 'VidPostanovi.pas' {frmVidPostanovi},
  VidPostanoviEdit in 'VidPostanoviEdit.pas' {frmVidPostanoviEdit},
  VidPostanoviSetting in 'VidPostanoviSetting.pas' {frmVidPostanoviSetting},
  VizmatiVinnim in 'VizmatiVinnim.pas' {frmVizmatiVinnim},
  VizmatiVinnimEdit in 'VizmatiVinnimEdit.pas' {frmVizmatiVinnimEdit},
  UmoviVidnovlenny in 'UmoviVidnovlenny.pas' {frmUmoviVidnovlenny},
  UmoviVidnovlennyEdit in 'UmoviVidnovlennyEdit.pas' {frmUmoviVidnovlennyEdit},
  VidomchaPidporydkovanistEdit in 'VidomchaPidporydkovanistEdit.pas' {frmVidomchaPidporydkovanistEdit},
  SumiShtrafu in 'SumiShtrafu.pas' {frmSumiShtrafu},
  SumiShtrafuEdit in 'SumiShtrafuEdit.pas' {frmSumiShtrafuEdit},
  Filter in 'Filter.pas' {frmFilter},
  VidomostiProOrganizaciju in 'VidomostiProOrganizaciju.pas' {frmVidomostiProOrganizaciju},
  Zvyzok in 'Zvyzok.pas' {frmZvyzok},
  ZvitShtrafi in 'ZvitShtrafi.pas' {frmZvitShtrafi},
  GlobalUsers in 'GlobalUsers.pas' {frmGlobalUsers},
  GlobalUsersEdit in 'GlobalUsersEdit.pas' {frmGlobalUsersEdit},
  Groups in 'Groups.pas' {frmGroups},
  GroupsEdit in 'GroupsEdit.pas' {frmGroupsEdit},
  AddMember in 'AddMember.pas' {frmAddMember},
  Koristuvachi in 'Koristuvachi.pas' {frmKoristuvachi},
  KoristuvachiEdit in 'KoristuvachiEdit.pas' {frmKoristuvachiEdit},
  Vikna in 'Vikna.pas' {frmVikna},
  ViknaEdit in 'ViknaEdit.pas' {frmViknaEdit},
  ElementiVikon in 'ElementiVikon.pas' {frmElementiVikon},
  ElementiVikonEdit in 'ElementiVikonEdit.pas' {frmElementiVikonEdit},
  PravaKoristuvachiv in 'PravaKoristuvachiv.pas' {frmPravaKoristuvachiv},
  RivniSES in 'RivniSES.pas' {frmRivniSES},
  RivniSESEdit in 'RivniSESEdit.pas' {frmRivniSESEdit},
  PrintForm in 'PrintForm.pas' {frmPrintForm},
  DataTypes in 'DataTypes.pas' {frmDataTypes},
  DataTypesEdit in 'DataTypesEdit.pas' {frmDataTypesEdit},
  DataTables in 'DataTables.pas' {frmDataTables},
  DataTablesEdit in 'DataTablesEdit.pas' {frmDataTablesEdit},
  FieldEdit in 'FieldEdit.pas' {frmFieldEdit},
  Reports in 'Reports.pas' {frmReports},
  ReportsEdit in 'ReportsEdit.pas' {frmReportsEdit},
  RerpotParamEdit in 'RerpotParamEdit.pas' {frmRerpotParamEdit},
  ChoiceVariable in 'ChoiceVariable.pas' {frmChoiceVariable},
  Initialize in 'Initialize.pas' {frmInitialize},
  InitializeEdit in 'InitializeEdit.pas' {frmInitializeEdit},
  splash in 'splash.pas' {frmSplash};

{$R *.res}

begin
  frmSplash:=TfrmSplash.Create(Application);
  frmSplash.Position:=poMainFormCenter;
  frmSplash.BorderStyle:=bsNone;
  frmSplash.Show;
  Application.Initialize;
  frmSplash.Update;
  Application.CreateForm(TfrmMain, frmMain);
  frmSplash.Hide;
  frmSplash.Free;
  Application.Run;
end.
